# Generated by Django 5.0.6 on 2024-05-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViajerosResidenciaDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_tiempo', models.DateField()),
                ('region_de_destino', models.CharField(max_length=25)),
                ('origen_viajeros', models.CharField(max_length=25)),
                ('viajeros', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
