# Generated by Django 5.0.6 on 2024-06-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viajerosresidenciadestino',
            options={'ordering': ['indice_tiempo', 'region_de_destino']},
        ),
    ]
