# Generated by Django 5.0.6 on 2024-06-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_alter_viajerosresidenciadestino_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajerosresidenciadestino',
            name='viajeros',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
